### ISSUE TITLE
config.gypi stripped no matter the path

### ISSUE THREAD

**Issue by mscdex** [npm/fstream-npm#13]
Can the `config.gypi` removal be restricted to `<module dir>/build` directories only instead of *anywhere*?

**Comment by othiym23** [comment]
This is a safety thing -- since `config.gypi` basically includes a scrape of the user's environment, it can (and has) leak sensitive information. My understanding is that this file is a cache that gets regenerated when `node-gyp`, so why do you want this packaged?

**Comment by mscdex** [comment]
Well, for example I was using the filename `config.gypi` for an addon (I am bundling the wrapped library, so the `config.gypi` file is actually inside `./deps/library/config`) of mine so i could have one include that pulled in platform-specific configurations. So now I am forced to change a filename for something unrelated to `node-gyp` itself. Kind of annoying...
